# Generated by Django 5.1.7 on 2025-04-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_remove_answer_answer_text_answer_scale_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pushover_user_key',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reminder_interval_hours',
            field=models.PositiveIntegerField(default=12),
        ),
    ]
