# Generated by Django 5.1.4 on 2025-04-18 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_customuser_pushover_user_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pushover_device_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
