# Generated by Django 5.1.7 on 2025-04-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_customuser_pushover_device_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pushover_app_token',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
