# Generated by Django 5.1.7 on 2025-04-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_customuser_pushover_app_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_reminder_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
